### ISSUE TITLE
Are rust functions still allowed?

### ISSUE THREAD

**Issue by ekwoka** [netlify/rust-functions-example#8]
Is this even possible to do Rust functions?

The blog says to do `functions:create --language=rust` but this fails.

**Comment by ekwoka** [comment]
closed:

Needed to add

```toml
[context.dev]
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }
```

to netlify.toml and select the serverless functions option to get a rust example
